### ISSUE TITLE
I cannot open console

### ISSUE THREAD

**Issue by ghost** [eschutz/atom-console#5]
When I use ctrl+alt+x shortcut I see the "ź" sign which is a character from my Polish language.

**Comment by eschutz** [comment]
Hi @Kacper777777, please provide more details.
What platform are you on? Where does the character appear, in the atom-console prompt or in the editing buffer?
Would it be possible to provide a screenshot?

Thanks.

**Comment by ghost** [comment]
Hi. I am using Windows 10. I have all the updates. The letter "ź" shows also in different places whenever I use this shortcut (for example in the browser). Maybe my language settings cause this problem. But I remember that it worked previously. 
![language](https://user-images.githubusercontent.com/50482739/71780845-c64aa700-2fc7-11ea-8ce5-f2a7cce3fc4c.png)
This character appears in the editing buffer.

**Comment by eschutz** [comment]
I imagine it is occurring because the input language is set to Polish (it seems 'alt-x' types ź, according to my brief research). You could try changing the keyboard shortcut to 'ctrl-ź' from Edit > Preferences > Keybinding, and setting the binding for 'atom-console:toggle' to 'ctrl-ź' (try typing 'ctrl-alt-x' normally and see if it works). However, this may break the shortcut on an English keyboard, if you use one.

If this method doesn't work, try changing the keyboard shortcut to something else that doesn't type another character.

Out of interest, have you had any issues with other keyboard shortcuts using a Polish keyboard?

**Comment by ghost** [comment]
It's the first time when my Polish keyboard caused a problem.
I changed the keyboard scheme to English and it works. I will use this keyboard scheme while coding. And I can easily switch into Polish if I need to communicate in Polish with my friends. It's just pressing windows+space and choosing a keyboard scheme.
